---
title: "TaxiDataset2"
author: "Kenta Sakamoto"
date: "2020/1/7"
output: html_document
---

# 目的
 - データを読み込んで、欠損値を除去したデータを作成する
 
# データの読み込み
```{r}
library(data.table)
JR201611 <- fread("../rawdata/monthly_201611/monthly_201611/monthly_201611_000000000024.csv",stringsAsFactors=FALSE, encoding="UTF-8")
```

# 欠損状況の確認と除去
```{r}
library(VIM)
aggr(JR201611,prop = FALSE,number = TRUE)
```

```{r}
JR201611 <- na.omit(JR201611)
```

```{r}
write.csv(JR201611,file = "../newdata/JR201611_04-09_15.csv")
```

# ファイル内のcsvファイルを一度に読み込む

```{r}
# データの存在するディレクトリを設定する
setwd("C:/Users/Kenta Sakamoto/Desktop/JR2/code_applied_reaserch/rawdata/monthly_201611/monthly_201611")
```

```{r}
# filesにデータを格納する
files <- list.files(path = "C:/Users/Kenta Sakamoto/Desktop/JR2/code_applied_reaserch/rawdata/monthly_201611/monthly_201611",full.names = T)
```

```{r}
JR201611 <- list()
for (i in 1:5) {
  JR201611[i] <- read.csv(files[i],fileEncoding = "UTF-8")
}
```

# 参考
https://teratail.com/questions/109979  
http://jojoshin.hatenablog.com/entry/2017/02/03/220118  
https://id.fnshr.info/2017/08/14/r-blank-row-col/